# Generated by Django 2.2.4 on 2019-08-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Style'),
        ),
    ]
